### ISSUE TITLE
Icon for Zowe subprojects, such as Zebra

### ISSUE THREAD

**Issue by Joe-Winchester** [openmainframeproject/artwork#22]
Zebra is an Zowe incubator project.  To identify it a request was made at a Zebra meeting whether there could be artwork that is based on the Zowe icon but rendered to show that it is Zebra.  Suggestions are to stripe/color the Z differently to look like Zebra animal coloring

**Comment by jmertic** [comment]
It's an interesting idea; what would be the full list of projects we would have logos for?

**Comment by Joe-Winchester** [comment]
I think the current two Zowe incubator projects are:

- Zebra (https://github.com/zowe/zebra - led by https://github.com/ykimvicom)
- Zowe mobile (https://github.com/zowe/zowe-on-the-go - led by https://github.com/jellypuno)

**Comment by jmertic** [comment]
Would there be artwork also for CLI, API Mediation Layer, etc?

**Comment by Joe-Winchester** [comment]
> Would there be artwork also for CLI, API Mediation Layer, etc?

Good question.  I wasn't thinking there would be as these are more Zowe components (CLI, Zowe Explorer, APIML, Zowe Desktop) so they all share the same Zowe branding which also helps to identify them as being part of Zowe core.  

Distinguishing the incubator projects with a decorated icon could help to recognize them as separate, which was Alex's ask.  I'd love to include him in this conversation but I don't think he's part of this repo so I couldn't @ him

**Comment by jmertic** [comment]
Tagging @ykimvicom

So it sounds like more of the ask is artwork around the non-Zowe core projects - is that probably a better descriptor?

**Comment by ykimvicom** [comment]
Thanks @jmertic @Joe-Winchester  - I think Joe summarized it nicely above there and yes John I think something can inherit Zowe core's identity at the same time something can represent its function(like desktop icon).  in a concept, I was thinking something like this(and I admit quicly I'm not a graphic designer =) https://zebra.talktothemainframe.com/zebra_icon.png  but thought it'd be against design guidelines so for now we are using Zowe logo for our test site : https://zebra.talktothemainframe.com/

**Comment by Joe-Winchester** [comment]
Lovely graphic @ykimvicom at https://zebra.talktothemainframe.com/zebra_icon.png !   It feels to me as it may be too much of a deviation from the original Zowe one however, so I wonder what it's look like with just the original and re-coloring, e.g. 

![image](https://user-images.githubusercontent.com/28100302/113688119-eaac9c00-96c0-11eb-97ae-23050a726f9e.png)

 (Note I am not a graphic artist so very rough and ready mock up but the original shape remains.  I think this helps with trademark protection to be within the shape that I recall from my days doing GUI builders trying to create variants on the IBM logo which is policed very heavily based on its shape and arrangement)

**Comment by jmertic** [comment]
Adding @jellypuno as she shared interest in this for Zowe Explorer as well.

**Comment by jellypuno** [comment]
Thank you! Zowe FTP VS Code extension is also interested in adding a logo with Zowe on it. 

@Joe-Winchester Do you think the CICS VSCode will use the Zowe logo as well?

**Comment by Joe-Winchester** [comment]
> @Joe-Winchester Do you think the CICS VSCode will use the Zowe logo as well?

@jellypuno , yes I think the CICS VS Code extension should have a logo for when it goes onto the marketplace, similar to the way the FTP one has been done.

At the moment I'm leaning towards the existing standard logo being used on all core projects and the annotated logos being used on incubators (Zebra, Mobile,  soon to be CICS), however when those incubators become core I'm not sure if they would want to lose their logo.  Maybe we have a Zowe background that is grey rather than blue that denotes a core, and the annotation like the Zebra filling or other annotation can carry forward from grey to blue when the project graduates.  

![image](https://user-images.githubusercontent.com/28100302/115721669-2eb4c780-a376-11eb-939f-0aa8939c1f18.png)

**Comment by ykimvicom** [comment]
@Joe-Winchester I love the variations of main Zowe logo - either adding zebra stripes or adding annotations look great to me. Giving different color shading(grey -> blue) when graduating sounds brilliant!

**Comment by jmertic** [comment]
Hey - this fell through the cracks and I want to bring this back up. What is a current list of squads/subprojects that we should have artwork for?

**Comment by Joe-Winchester** [comment]
Hi @jmertic.
For incubator projects that could use some nice Zowe themed artwork

[Zebra](https://www.zowe.org/#zebra-intro)
[Zowe Chat](https://www.zowe.org/#chat-intro)
[Zowe Mobile](https://www.zowe.org/#zowe-mobile-intro).

**Comment by jmertic** [comment]
Great - thanks @Joe-Winchester - what core components also make sense to have artwork for? Explorer?

**Comment by Joe-Winchester** [comment]
@jmertic .  For the core Zowe Explorer component it currently uses the regular Zowe Z symbol, so I'm not sure whether it needs its own graphic.  However it is a good thought as to whether Zowe CLI, Zowe Explorer, Zowe Desktop and Zowe APIML deserve separate graphics of their own.

I think this is a Zowe TSC question, so I'll forward the issue to Jakub and we can bring it up on the TSC agenda and also get input from the other squad leads.   

![image](https://user-images.githubusercontent.com/28100302/169849670-73334035-be78-4b65-92d8-5f7dd23ae75d.png)

**Comment by behives** [comment]
Thanks John and Joe!

sorry catching late.

For Zebra, the core concept representing would be 'waves' that resembled
zebra's pattern - I was hoping to make it look like many of system
utilization reports/graphs that are wavy. Anything shows Zowe/Z could help
too.

Thanks a lot!

Alex

**Comment by jmertic** [comment]
@Joe-Winchester - any feedback from the TSC?

**Comment by jmertic** [comment]
Any TSC feedback on this?

**Comment by jmertic** [comment]
Similar effort related to Zowe Chat at https://github.com/zowe/zowe-chat/issues/122

**Comment by behives** [comment]
Thanks @jmertic  - to make sure understand what you need, do you need which subproject(s) need the icon(s)? do you also need prioritized list? I see Zowe chat branding is in TSC topic for tomorrow's call.

**Comment by Joe-Winchester** [comment]
Hi @jmertic .  For the CICS logo we did actually get a designer on the IBM team to create the graphic for us.  There is a different logo for CICS Transaction Server that they specifically didn't want to be used by Zowe, and the one that is overlaid across the Zowe logo is public domain.   When the plugin was named the IBM team asked that we didn't call it "Zowe CICS Explorer" and instead call it "Zowe Explorer for IBM CICS" which fits in with tradmark usage so we did that.
Outside of the VS Code marketplace the graphics are used in blogs on medium.com/zowe (for example if there is a Zowe Explorer for IBM CICS piece) the graphic is used.  Likewise on social media posts, conference presentations, and other material associated with the plugin.
For the FTP extension, I don't think anyone has provenance over trademark usage of the word "FTP", so the squad just did the manual dropping of FTP on top.  This was done in November 2020 when the plugin was first released (so it's been used for over two years).  
My concern about reverting all of the items to the same base icon, is that it will confuse users who are distinguishing each of the functionally separately and want to know which is which.  Other orgs (Iike Microsoft or other IT companies) who publish many extensions do separate each of them with different branded icons but based on a background theme that indicates their provenance as being from Microsoft but with overlays that cover the functional areas.

**Comment by Joe-Winchester** [comment]
@jmertic ,  other squads are creating their own icons.  See https://github.com/zowe/docs-site/issues/1606#issuecomment-1342728216 which is the IntelliJ graphic, and also the Zowe Chat squad has been creating their own artwork that is based on the Zowe icon but with a themed addition/overlay.

**Comment by jmertic** [comment]
Thanks for sharing @Joe-Winchester. We've chatted on this before that it would be great for the subprojects to share thier icon needs with us so we can work with the in-house CS team on artwork. Our goal is to ensure the project has the artwork it needs to be successful; I feel bad the project is spinning it's wheels on artwork like this.

**Comment by Joe-Winchester** [comment]
That'll be great if your in-house CS team can work on the artwork.  What's the best way we can raise this requirement ?  
The immediate need would be to have graphics for the Zowe Explorer FTP and Zowe Explorer for IBM CICS extensions (i.e. the two that you want removed).    I am concerned that if the public icons revert to the default Zowe icon in the community (as covered above the two icons you have asked to be removed have been in the community for 2 years and 1 1/2 years respectively) then this will cause confusion as all 3 extensions will look like the base plugin which is different functionality.  Can we leave the icons as-is in the VS code marketplace until the in-house team have created your own artwork ?
Following that the next would be an icon for the Zowe Chat project.
Cheers !

**Comment by jmertic** [comment]
Great! For each icon we will need the attached logo brief to be completed...

[Logo Creative Brief-MAKE A COPY.docx](https://github.com/openmainframeproject/artwork/files/10217811/Logo.Creative.Brief-MAKE.A.COPY.docx)

We also need examples of where the artwork will be used.

As for the other comments...

- I chatted with the Zowe Chat folks and they indicated they were sticking with the main Zowe imagery. The use case there was a bit different, as it was discussed that it would cause more confusion to have a seperate brand in the chat client vs using the main Zowe branding
- I am concerned on the CICS one specifically as that does resemble the IBM brand. Unless you can provide the licensing and terms for reuse, we can't keep using that icon.

Thanks for helping wrangle this in!

**Comment by Joe-Winchester** [comment]
These are the icon requests.  Cheers ! 

[Logo.Creative.Brief-ZOWECICSEXPLORER.docx](https://github.com/openmainframeproject/artwork/files/10240263/Logo.Creative.Brief-ZOWECICSEXPLORER.docx)

[Logo.Creative.Brief-ZOWEFTPEXPLORER.docx](https://github.com/openmainframeproject/artwork/files/10240329/Logo.Creative.Brief-ZOWEFTPEXPLORER.docx)

**Comment by jmertic** [comment]
I've put in these requests now. With the holidays, I would expect first drafts after the new year.

**Comment by jmertic** [comment]
Here are the mockups for review...

[Zowe_FTP_Icon_v1.zip](https://github.com/openmainframeproject/artwork/files/10457012/Zowe_FTP_Icon_v1.zip)
[Zowe_CICS_Icon_v1.zip](https://github.com/openmainframeproject/artwork/files/10457014/Zowe_CICS_Icon_v1.zip)

Is there also interest in a Zebra icon? If so we should get a creative brief for that project too.

**Comment by jmertic** [comment]
I think for the ones with a design in the Z, I would anticipate there wouldn't be transparency since as you said it wouldn't make sense.

No other real patterns for other extensions in mind; I think at this stage we are just trying to get feedback on the mockups and then can think about how this rolls out for other projects.

**Comment by Joe-Winchester** [comment]
For the FTP and CICS icons my favorite is the Logo_3.png in both cases.   

I wonder if it's possible to play around a little with the font of the words `CICS`.  I grabbed some images below from doing an "IBM CICS" search as something was a little off in my untrained eye, but I think it's maybe the curving on the C letters.  Generally whenever I see `CICS` written the Cs are rounded,  and for the Logo_3.png icon it has a slightly different shape.   Maybe the font style or stroke width or aspect ratio can be altered ?
See below.

![image](https://user-images.githubusercontent.com/28100302/213815304-8ab766b9-e7f7-4f60-a03b-cda03f2a3942.png)

![image](https://user-images.githubusercontent.com/28100302/213815468-50823022-cf12-473c-9b02-1da67ae79f54.png)

<img width="258" alt="image" src="https://user-images.githubusercontent.com/28100302/213818835-5380553e-3442-4e27-bd40-5f3b840f8a42.png">


On the other question about the existing Zowe graphic and transparency this is a known problem that it'd be great if you have time to address ?  For example in VS Code in dark mode the black background bleeds through and having the Z being white could look better (which matches the appearance on the marketplace or VS Code in light mode).  See screen shots below.

<img width="931" alt="image" src="https://user-images.githubusercontent.com/28100302/213814796-25695e0e-0f64-4beb-b39f-9d4e1c4cb9f7.png">
<img width="204" alt="image" src="https://user-images.githubusercontent.com/28100302/213815100-55371487-3033-430e-a980-636f7c3b2e16.png">

This is great progress so thank you !    Sorry being nitpickey.

**Comment by jmertic** [comment]
Thanks @Joe-Winchester! Let me know when I should go back to the designers with this feedback, as well as direction on which icon most closely resembles what the community wants to pursue.

@balhar-jakub Let me know if having this as a topic at a TSC meeting would be more appropriate.

**Comment by balhar-jakub** [comment]
@jmertic Unless you need some topic specifically, I don't really see this as a topic that most of the TSC members other than the ones already involved has an opinion on. 

I will bring it to the onboarding squad, there may be more people with an opinion.

**Comment by jmertic** [comment]
That's fine - I just want to be certain there is proper visability on the plan here. I'll leave it to you to guide towards the righr group.

**Comment by jmertic** [comment]
Any updates from onboarding?

**Comment by Joe-Winchester** [comment]
> Any updates from onboarding?

I've missed the last two onboarding calls as I was travelling (to mainframe customers using Zowe which was nice !).  I'll add it to the agenda for the upcoming Friday onboarding call.

Thanks again for moving this forward.  Very much appreciated by all.

**Comment by JillieBeanSim** [comment]
Hey @jmertic we discussed this topic today at the Onboarding meeting and from the designs presented we agreed on the logos that include the Z with different variations.
Zowe FTP icon (Logo 2)

![Logo 2](https://user-images.githubusercontent.com/49491949/216701193-484e4467-6bdd-428e-bf1e-d27574160882.png)


Zowe CICS icon (Logo 1)

![Logo 1](https://user-images.githubusercontent.com/49491949/216701160-6c5a6391-2d73-40d9-8aeb-caebfcb08674.png)

**Comment by jmertic** [comment]
Thanks! Will have the designers review and get final versions to you.

**Comment by jmertic** [comment]
Artwork added at https://artwork.openmainframeproject.org/projects/zowe/

Closing this and we can open new issues for any other artwork needed.

**Comment by JillieBeanSim** [comment]
> Thanks! Will have the designers review and get final versions to you.

Thanks @jmertic
