### ISSUE TITLE
GenevaERS Logo Sample

### ISSUE THREAD

**Issue by KipTwitchell** [openmainframeproject/artwork#8]
This was a logo for GenevaERS from the 1990's.  It has not been used for years.  It could be considered for use in creating a GenevaERS logo.
![Geneva ERS Icon](https://user-images.githubusercontent.com/29467627/88219616-795ab500-cc27-11ea-8b17-084f9af3e521.jpeg)

**Comment by AOrthVector** [comment]
My GenX self loves it

**Comment by jmertic** [comment]
Closing as we've aligned on the logo in #10
